config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'login#new'
  post 'create_board', to: 'login#create'
  get 'boards/:id/:nickname', to: 'boards#show', as: 'boards'
  post '/boards/:id/:beer_index', to: 'boards#update', as: 'update_board'
  get 'drink_log', to: 'drink_log#index'
  get 'leader_board', to: 'leader_board#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  after_create :generate_board

  BALTER_BEERWORKS = ['Good Neighbor', 'Maypop', 'Firebelly', 'Bear Blend']
  ALLIANCE_BREWING_COMPANY = ['Citra Blonde', 'Citra Mosaic Simcoe IPA',
    'Cubano coffee Brown', 'Kolsch', 'Outmeal Stout', 'Saison 4', 'Scotch Ale']
  PRETENTIOUS_BREWING_COMPANY = ['Perennial Smoke, Rosemary', 'Glassholes, Amarillo & Mosaic Edition',
    'Shout Out Saison', 'Imperial Table (tennis) Beer', 'Cathedral V. Enigma',
    'Honey Honey Honey', 'New Kids On the Floc', 'Abandoned Belgian Mansion With A View of A Vineyard',
    'Cowboy Henk, A Belgo', 'Clammy Wallop', 'Sultry V. Adam With Peaches, Pomegranate And White Tea',
    'Da Dank Drank', 'Two Legged Snake, Azacca Edition', 'Televangelist, An Al Pastor DIPA',
    '#superdupertrendyAF, Blueberry Pomegranate Creamsicle', 'Old School Is the New New School',
    'Attaboy', 'Surly Mistress', 'Burly Mistress', "Where There's Smoke, There's Fire",
    'Samuel Jackson’s M——- F——- Rye Wine', 'Beyond Logic And Raisin']
  LAST_DAYS_OF_AUTUMN = ['Pardon My Garden Double IPA', 'Pardon My Garden IPA', 'Biff’s Best IPA',
    'Juicy J IPA Series', 'Rye Pale Ale', 'Rye Pale Ale', 'Chamhopnay', 'Sharkbait Blonde Ale',
    'Last Days Berliner Weisse', 'Kentucky Common', 'Double Salted Caramel Porter',
    'Smoked Brown Ale', 'Delph’s Coffee Stout', 'Pre Prohibition Ale']
  CRAFTY_BASTARD = ['ESB', 'Vanilla Stout', 'Crafty Bastard Stratosphere 11.0',
    'Bourbon Barrel Imperial Scotch Ale', 'Framboise', 'Spicy Ginger Ale',
    'The Crafty Russian Imperial Stout', 'Big Bastard DIPA', 'Imperial Milk Stout',
    'Tessellation IPA', 'Hop Candy IPA']
  ELKMONT_EXCHANGE = ['Wheat & Rye Lager', 'Elkmont Table Beer With Blackberry',
    'Light Lager', 'Vienna Lager', 'Hefeweizen', 'American Pale Ale', 'India Pale Lager (IPL)',
    'Elkmont Table Beer', 'Norwegian Farmhouse Ale with Butternut Squash',
    'Norwegian Farmhouse Ale with Roasted Peaches', 'Post Modern Funk', 'Botanical Rye Farmhouse Ale',
    'Brown Ale', 'Outmeal Stout', 'Imperial Stout', 'IPA', 'Multigrain IPA', 'Rye IPA',
    'Wild IPA', 'Hoppy Belgian', 'Double IPA', 'Coffee Lager', 'Light Lager With Grapefruit',
    'Barrel Aged Smoked & Spiced Porter']
  DOWNTOWN_GRILL_AND_BREWERY = ['White Mule Ale', 'Woodruff IPA', 'New World Porter', 'Nut Brown Ale',
    'State Street Stout', 'Downtown Blonde Ale', 'Alt', "Grey Beard's Barley Wine"]
  BREWERIES = [PRETENTIOUS_BREWING_COMPANY, LAST_DAYS_OF_AUTUMN,
    BALTER_BEERWORKS, ALLIANCE_BREWING_COMPANY, CRAFTY_BASTARD,
    ELKMONT_EXCHANGE, DOWNTOWN_GRILL_AND_BREWERY]
  def generate_board
    25.times do
      beer = BREWERIES.sample.sample
      compressed_beers = beers.map{ |x| x[:beer] }

      while compressed_beers.include?(beer)
        beer = BREWERIES.sample.sample
      end
      beers << { beer: beer, drank: false }
    end
    beers[12] = { beer: 'Get on the bus', drank: true}
    save
  end
end

app/models/drank.rb
class Drank < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:update]

  def show
    @board = Board.find_by(nickname: params[:nickname], id: params[:id])
    @drink_log = Drank.where("created_at >= :date", date: DateTime.now.beginning_of_day)
    @boards = leader_board
  end

  def update
    @board = Board.find_by(id: params[:id])
    beer_index = params[:beer_index].to_i
    to_update = @board.beers[beer_index]
    to_update['drank'] = !to_update['drank']
    @board.distance = distance
    @board.save
    drank = Drank.find_or_create_by(beer: to_update['beer'], drinker: @board.nickname)
    drank.destroy unless to_update['drank']
  end

  def leader_board
    Board.where("created_at >= :date", date: DateTime.now.beginning_of_day).sort {|x,y| y.distance <=> x.distance }
  end

  def distance
    rows = []
    5.times do |x|
      rows << @board.beers[(x*5)..((x+1)*5 - 1)]
    end

    counts = []
    rows.each do |row|
      count = 0
      row.each do |beer|
        count += 1 unless beer['drank']
      end
      counts << count
    end

    5.times do |i|
      count = 0
      5.times do |j|
        count += 1 unless rows[j][i]['drank']
      end
      counts << count
    end

    count = 0
    5.times do |i|
      count += 1 unless rows[i][i]['drank']
    end
    counts << count

    count = 0
    5.times do |i|
      count += 1 unless rows[i][4-i]['drank']
    end
    counts << count

    counts.min
  end
end

app/controllers/drink_log_controller.rb
class DrinkLogController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:index]

  def index
    @drink_log = Drank.all
    render partial: 'drink_log'
  end
end

app/controllers/leader_board_controller.rb
class LeaderBoardController < ApplicationController
  def index
    @boards = leader_board
    render partial: 'leader_board'
  end

  def leader_board
    Board.all.sort {|x,y| y.distance <=> x.distance }
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def create
    board = Board.find_or_create_by(nickname: params[:board][:nickname])
    if board.created_at < DateTime.new.beginning_of_day
      board.delete
      board = Board.create(nickname: params[:board][:nickname])
    end
    redirect_to boards_path(id: board.id, nickname: board.nickname)
  end

  def new
    @board = Board.new
    @drink_log = Drank.where("created_at >= :date", date: DateTime.now.beginning_of_day)
    @boards = leader_board
  end

  def leader_board
    Board.where("created_at >= :date", date: DateTime.now.beginning_of_day).sort {|x,y| y.distance <=> x.distance }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/drink_log_helper.rb
module DrinkLogHelper
end

app/helpers/leader_board_helper.rb
module LeaderBoardHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/boards/show.html.erb
<table id="bingo-board" style="height: 50%;">
  <% @board.beers.each_with_index do |beer, index| %>
    <% if (index + 1) % 5 == 1 %>
      <tr style="height: 182px; padding: none">
    <% end %>
    <td style="max-width: 20%; border-style: solid; background-color: black">
      <button id="<%= "#{@board.id}/#{index}" %>" class="bingo-button" style="text-align: center; width: 100%; height: 100%; background-color: <%= beer['drank'] ? 'lightgreen;' : 'white;' %>">
        <h1><%= beer['beer'] %></h1>
      </button>
    </td>
    <% if (index + 1) % 5 == 0 %>
      </tr>
    <% end %>
  <% end %>
</div>

app/views/drink_log/_drink_log.html.erb
<table id="drink_log">
  <% @drink_log.reverse_each do |drank| %>
    <tr>
      <td>
        <% zone = ActiveSupport::TimeZone.new('Eastern Time (US & Canada)') %>
        <%= "#{drank.created_at.in_time_zone(zone).strftime('%l:%M %p')} #{drank.drinker} drank a #{drank.beer}" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bingo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <table style="height: 50%; width: 100%; border-style: solid;">
      <tr>
        <td style="text-align: center; border-style: solid;">
          <h1>Drink Log</h1>
        </td>
        <td style="text-align: center; border-style: solid;">
          <h1>Leader Board</h1>
        </td>
      </tr>
      <tr>
        <td style="max-width: 50%">
          <div style="overflow-y: scroll; height: 300px; border-style: solid;">
            <%= render 'drink_log/drink_log' %>
          </div>
        </td>
        <td style="max-width: 50%">
          <div style="overflow-y: scroll; height: 300px; border-style: solid;">
            <%= render 'leader_board/leader_board' %>
          </div>
        </td>
      </tr>
    </table>
  </body>
</html>

app/views/leader_board/_leader_board.html.erb
<table id="leader_board">
  <% index = 0 %>
  <% @boards.reverse_each do |board| %>
    <tr>
      <td>
        <%= "#{index+1}. #{board.nickname}" %>
      </td>
      <td style="text-align: right">
        <% if board.distance == 0 %>
          <%= "BINGO!" %>
        <% else %>
          <%= "#{board.distance} beers to go" %>
        <% end %>
      </td>
    </tr>
    <% index += 1 %>
  <% end %>
</table>

app/views/login/index.html.erb
<h1>Hello world</h1>

app/views/login/new.html.erb
<%= simple_form_for @board, url: create_board_path, method: :post do |f| %>
  <%= f.input :nickname, required: true %>
  <%= f.button :submit, 'Get Bingo Board!'%>
<% end %>